version: '3.8'

services:
  api:
    build:
      context: ./api
      # Usa o est√°gio 'development' do Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      # Monta o volume para live reload
      - ${PWD}/api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: db
      DB_USER: user_docker
      DB_PASSWORD: password_docker
      DB_NAME: mydatabase
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user_docker
      POSTGRES_PASSWORD: password_docker
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: