services:
  # 1. Serviço da API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    # Variáveis de ambiente para a API se conectar ao DB
    environment:
      # O hostname do DB é o nome do serviço no Compose: 'db'
      DB_HOST: db
      DB_USER: user_docker
      DB_PASSWORD: password_docker
      DB_NAME: mydatabase
    # Garante que o DB inicie antes da API
    depends_on:
      - db

  # 2. Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:16-alpine # Imagem oficial leve
    # Variáveis de ambiente para configurar o PostgreSQL
    environment:
      POSTGRES_USER: user_docker
      POSTGRES_PASSWORD: password_docker
      POSTGRES_DB: mydatabase
    # Configura um volume nomeado para persistência dos dados
    volumes:
      - db_data:/var/lib/postgresql/data

# Define o volume nomeado
volumes:
  db_data:

  